# Generated by Django 5.2.5 on 2025-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
